"""add debate models

Revision ID: 46ec214b784e
Revises: 03774e9b78c8
Create Date: 2026-04-16 17:02:25.973850

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "46ec214b784e"
down_revision: Union[str, Sequence[str], None] = "03774e9b78c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("system_prompt", sa.String(), nullable=False),
        sa.Column("avatar", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_name"), ["name"], unique=True)

    op.create_table(
        "debate",
        sa.Column("topic", sa.String(length=500), nullable=False),
        sa.Column("max_rounds", sa.Integer(), nullable=False),
        sa.Column("current_round", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "IN_PROGRESS", "COMPLETED", "STOPPED", name="debatestatus"
            ),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "debateparticipant",
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("debate_id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agent.id"],
        ),
        sa.ForeignKeyConstraint(
            ["debate_id"],
            ["debate.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("debateparticipant", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_debateparticipant_agent_id"), ["agent_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_debateparticipant_debate_id"), ["debate_id"], unique=False
        )

    op.create_table(
        "message",
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("debate_id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("participant_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("STREAMING", "COMPLETE", name="messagestatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agent.id"],
        ),
        sa.ForeignKeyConstraint(
            ["debate_id"],
            ["debate.id"],
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["debateparticipant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_message_agent_id"), ["agent_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_message_debate_id"), ["debate_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_message_participant_id"), ["participant_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_message_participant_id"))
        batch_op.drop_index(batch_op.f("ix_message_debate_id"))
        batch_op.drop_index(batch_op.f("ix_message_agent_id"))

    op.drop_table("message")
    with op.batch_alter_table("debateparticipant", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_debateparticipant_debate_id"))
        batch_op.drop_index(batch_op.f("ix_debateparticipant_agent_id"))

    op.drop_table("debateparticipant")
    op.drop_table("debate")
    with op.batch_alter_table("agent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_name"))

    op.drop_table("agent")
    # ### end Alembic commands ###
